import dataclasses as dt
import hashlib
import math
import os
import random
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any, Literal, TypeVar

import paramiko
from paramiko.channel import ChannelFile, ChannelStdinFile

from . import logger

DEFAULT_PRIVATE_KEY_NAMES = [
    "id_rsa",  # RSA (deprecated and not generated by default on many systems)
    "id_ecdsa",  # ECDSA
    "id_ecdsa_sk",  # ECDSA with FIDO/U2F
    "id_ed25519",  # Ed25519
    "id_ed25519_sk",  # Ed25519 with FIDO/U2F
]

T = TypeVar("T")


@dt.dataclass(frozen=True)
class SessionContent:
    stdout: str
    stderr: str

    @classmethod
    def from_channel(cls, channel: paramiko.Channel) -> "SessionContent":
        return cls(
            stdout=channel.recv(4096).decode("utf-8"),
            stderr=channel.recv(4096).decode("utf-8"),
        )

    @classmethod
    def from_command(
        cls,
        channel_stdin: ChannelStdinFile,
        channel_stdout: ChannelFile,
        channel_stderr: ChannelFile,
    ) -> "SessionContent":
        return cls(
            stdout=channel_stdout.read().decode("utf-8"),
            stderr=channel_stderr.read().decode("utf-8"),
        )

    def __str__(self) -> str:
        return f"stdout: {self.stdout.strip()}\nstderr: {self.stderr.strip()}"


class TemporaryConnectionError(RuntimeError):
    """Transient SSH/SFTP failure that should be retried with a fresh connection."""


class FinalConnectionError(RuntimeError):
    """SSH/SFTP failure after all retry attempts have been exhausted."""


class Session:
    def __init__(
        self,
        instance_id: str,
        region: str | None = None,
        private_key_path: str | None = None,
        user: str | None = None,
        client: Any = None,
        cloud: Literal["aws", "gcp"] = "aws",
        gcp_project: str | None = None,
        banner_timeout: int = 5,
        connect_jitter: float | None = None,
        connect_retries: int = 5,
        connect_delay: float = 1.0,
    ):
        if cloud == "gcp":
            from .gcp_instance import InstanceInfo as GCPInstanceInfo
            from .gcp_instance import InstanceStatus as GCPInstanceStatus

            # there is no default for GCP, so user must provide one
            if user is None:
                raise ValueError("user must be provided for GCP instances")

            self.instance = GCPInstanceInfo.describe_instance(
                instance_id=instance_id, region=(region or "us-central1"), gcp_project=gcp_project, client=client
            )
            self.InstanceStatus = GCPInstanceStatus
        else:
            from .aws_instance import InstanceInfo as AWSInstanceInfo
            from .aws_instance import InstanceStatus as AWSInstanceStatus

            # default for AWS is ec2-user
            user = user or "ec2-user"

            self.instance = AWSInstanceInfo.describe_instance(
                instance_id=instance_id, region=(region or "us-east-1"), client=client
            )
            self.InstanceStatus = AWSInstanceStatus

        self.private_key_path = private_key_path
        self.user = user
        self.banner_timeout = banner_timeout
        self.connect_jitter = connect_jitter
        self.connect_retries = connect_retries
        self.connect_delay = connect_delay

    def make_ssh_client(self) -> paramiko.SSHClient:
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        return client

    def _connect_once(self, attempt: int) -> paramiko.SSHClient:
        host = self.instance.public_ip_address
        base_delay = self.connect_delay * (2 ** (attempt - 1))
        max_jitter = self.connect_jitter if self.connect_jitter is not None else 0.5 * math.sqrt(base_delay)
        jitter = random.uniform(0, max_jitter)
        delay = base_delay + jitter

        logger.debug(
            f"[{host}] Connection attempt {attempt}/{self.connect_retries}, "
            f"waiting {delay:.1f}s before connecting "
            f"({base_delay:.1f}s base + {jitter:.1f}s jitter)..."
        )
        time.sleep(delay)

        client = self.make_ssh_client()
        try:
            logger.debug(f"[{host}] Connecting (banner_timeout={self.banner_timeout}s)...")
            client.connect(
                hostname=self.instance.public_ip_address,
                username=self.user,
                banner_timeout=float(self.banner_timeout),
                key_filename=self.private_key_path if self.private_key_path else None,
            )
            logger.debug(f"[{host}] Connected successfully on attempt {attempt}/{self.connect_retries}")
            return client
        except Exception:
            client.close()
            raise

    def _is_retryable_connection_error(self, error: Exception) -> bool:
        if isinstance(error, FinalConnectionError):
            return False

        return isinstance(
            error,
            (
                TemporaryConnectionError,
                EOFError,
                OSError,
                TimeoutError,
                paramiko.SFTPError,
                paramiko.SSHException,
            ),
        )

    def _wrap_connection_error(self, operation: str, attempt: int, retries: int, error: Exception) -> Exception:
        host = self.instance.public_ip_address

        if isinstance(error, FinalConnectionError):
            return error

        if not self._is_retryable_connection_error(error):
            return error

        message = str(error).strip() or error.__class__.__name__
        if attempt == retries:
            return FinalConnectionError(f"[{host}] {operation} failed after {retries} attempts: {message}")

        return TemporaryConnectionError(f"[{host}] {operation} failed on attempt {attempt}/{retries}: {message}")

    def _with_connection_retries(
        self,
        operation: str,
        action: Callable[[paramiko.SSHClient], T],
    ) -> T:
        for attempt in range(1, self.connect_retries + 1):
            client: paramiko.SSHClient | None = None
            try:
                client = self._connect_once(attempt)
                return action(client)
            except Exception as error:
                wrapped_error = self._wrap_connection_error(operation, attempt, self.connect_retries, error)
                if isinstance(wrapped_error, TemporaryConnectionError):
                    logger.warning(str(wrapped_error))
                    continue
                if isinstance(wrapped_error, FinalConnectionError):
                    logger.error(str(wrapped_error))
                    raise wrapped_error from error
                raise
            finally:
                if client is not None:
                    client.close()

        raise FinalConnectionError(f"[{self.instance.public_ip_address}] {operation} failed unexpectedly")

    def connect(self) -> paramiko.SSHClient:
        for attempt in range(1, self.connect_retries + 1):
            try:
                return self._connect_once(attempt)
            except Exception as error:
                wrapped_error = self._wrap_connection_error("SSH connect", attempt, self.connect_retries, error)
                if isinstance(wrapped_error, TemporaryConnectionError):
                    logger.warning(str(wrapped_error))
                    continue
                if isinstance(wrapped_error, FinalConnectionError):
                    logger.error(str(wrapped_error))
                    raise wrapped_error from error
                raise

        raise FinalConnectionError(f"[{self.instance.public_ip_address}] SSH connect failed unexpectedly")

    def shell(self, client: paramiko.SSHClient) -> paramiko.Channel:
        # Get local terminal size
        term_width, term_height = (t := shutil.get_terminal_size()).columns, t.lines

        # Open a channel and invoke a shell
        channel = client.invoke_shell()

        # Set the remote terminal size to match local terminal
        channel.resize_pty(width=term_width, height=term_height)

        return channel

    def _run_single_once(
        self,
        client: paramiko.SSHClient,
        command: str,
        timeout: int | None = None,
        get_pty: bool = False,
    ) -> SessionContent:
        host = self.instance.public_ip_address
        logger.debug(f"[{host}] Running command via exec_command...")
        response = client.exec_command(command, timeout=timeout, get_pty=get_pty)
        result = SessionContent.from_command(*response)
        logger.debug(f"[{host}] Command completed")
        return result

    def run_single(self, command: str, timeout: int | None = None, get_pty: bool = False) -> SessionContent:
        return self._with_connection_retries(
            operation="command execution",
            action=lambda client: self._run_single_once(client, command, timeout=timeout, get_pty=get_pty),
        )

    def _run_in_screen_once(
        self,
        client: paramiko.SSHClient,
        command: str,
        detach: bool = False,
        timeout: int | None = None,
        terminate: bool = True,
    ) -> SessionContent:
        host = self.instance.public_ip_address
        logger.debug(f"[{host}] Checking if screen is installed...")
        _, stdout, _ = client.exec_command("which screen")
        if "screen" not in stdout.read().decode("utf-8"):
            raise RuntimeError("screen is not installed; cannot run in screen")

        command_hash = hashlib.md5(command.encode()).hexdigest()[:12]

        logger.debug(f"[{host}] Connected, starting screen session...")

        channel = self.shell(client)

        # Create a new screen session
        screen_name = f"{__package__}-{command_hash}-{time.time()}"
        channel.send(f"screen -S {screen_name}\n".encode("utf-8"))
        time.sleep(0.1)  # Wait for screen to initialize

        completion_marker = f"CMD_COMPLETED_{command_hash[:20]}"

        # send the command to the server
        if terminate:
            channel.send(f"{command}; echo '{completion_marker}'; screen -X quit".encode("utf-8"))
        else:
            channel.send(f"{command}; echo '{completion_marker}'".encode("utf-8"))

        # send enter to run the command
        channel.send(b"\n")

        # Wait for the command to complete (looking for our marker)
        buffer = ""
        start_time = time.time()

        if detach:
            # sleep 1 second to ensure the command has time to communicate with the server
            time.sleep(1)
            # Detach from screen (Ctrl+A, then d)
            channel.send(b"\x01d")
        else:
            while True:
                # Check if we have data to receive
                if channel.recv_ready():
                    chunk = channel.recv(4096).decode("utf-8")
                    buffer += chunk

                    # Print to stdout in real-time
                    sys.stdout.write(chunk)
                    sys.stdout.flush()

                    # Check if our completion marker is in the output
                    if re.search(r"\r?\n" + completion_marker + r"\r?\n", buffer):
                        break

                # Check for timeout
                if timeout and time.time() - start_time > timeout:
                    logger.warning(f"\nTimeout waiting for command: {command}")
                    break

                # Small delay to prevent CPU spinning
                time.sleep(0.1)

        return SessionContent(stdout=buffer, stderr=buffer)

    def run_in_screen(
        self,
        command: str,
        detach: bool = False,
        timeout: int | None = None,
        terminate: bool = True,
    ) -> SessionContent:
        return self._with_connection_retries(
            operation="screen command execution",
            action=lambda client: self._run_in_screen_once(
                client,
                command,
                detach=detach,
                timeout=timeout,
                terminate=terminate,
            ),
        )

    def run(
        self,
        command: str,
        get_pty: bool = False,
        detach: bool = False,
        terminate: bool = True,
        timeout: int | None = None,
    ) -> SessionContent:
        if self.instance.state != self.InstanceStatus.RUNNING:
            raise ValueError(f"Instance {self.instance.instance_id} is not running")

        if detach:
            return self.run_in_screen(command, detach=detach, terminate=terminate, timeout=(timeout or 600))
        else:
            return self.run_single(command, get_pty=get_pty, timeout=timeout)

    def upload_files(
        self,
        local_paths: list[str],
        remote_dir: str | None = None,
    ) -> tuple[str, list[str]]:
        """Upload local files to the remote instance via SFTP.

        Args:
            local_paths: Local file paths to upload.
            remote_dir: Remote destination directory. If None, creates a temp
                directory on the remote machine using mktemp.

        Returns:
            Tuple of (remote_dir, list of remote file paths).
        """
        if self.instance.state != self.InstanceStatus.RUNNING:
            raise ValueError(f"Instance {self.instance.instance_id} is not running")

        return self._with_connection_retries(
            operation="file upload",
            action=lambda client: self._upload_files_once(client, local_paths, remote_dir),
        )

    def _upload_files_once(
        self,
        client: paramiko.SSHClient,
        local_paths: list[str],
        remote_dir: str | None = None,
    ) -> tuple[str, list[str]]:
        host = self.instance.public_ip_address
        logger.debug(f"[{host}] Uploading {len(local_paths)} file(s) via SFTP...")
        remote_dir_ = remote_dir

        try:
            if remote_dir_ is None:
                _, stdout, stderr = client.exec_command("mktemp -d")
                remote_dir_ = stdout.read().decode("utf-8").strip()
                if not remote_dir_:
                    err = stderr.read().decode("utf-8").strip()
                    raise RuntimeError(f"Failed to create remote temp directory: {err}")
            else:
                _, stdout, _ = client.exec_command(f"mkdir -p {remote_dir_}")
                stdout.channel.recv_exit_status()

            logger.debug(f"[{host}] Uploading to {remote_dir_}...")
            sftp = client.open_sftp()
            try:
                remote_paths = []
                for local_path in local_paths:
                    filename = os.path.basename(local_path)
                    remote_path = f"{remote_dir_}/{filename}"
                    logger.debug(f"[{host}] Uploading {filename} -> {remote_path}")
                    sftp.put(local_path, remote_path)
                    sftp.chmod(remote_path, 0o755)
                    remote_paths.append(remote_path)
            finally:
                sftp.close()

            logger.debug(f"[{host}] Upload complete ({len(remote_paths)} file(s))")
        finally:
            pass

        return remote_dir_, remote_paths

    def _prepare_file(self, temp_dir: Path, contents: str, script_name: str) -> Path:
        script_path = Path(script_name)
        script_md5 = hashlib.md5(script_bytes := contents.encode("utf-8")).hexdigest()[:8]
        script_base = script_path.name.removesuffix((script_ext := "".join(script_path.suffixes)))
        new_script_path = temp_dir / f"{script_base}_{script_md5[:8]}{script_ext}"

        with open(new_script_path, "wb") as f:
            f.write(script_bytes)

        # preserve existing permissions and make executable
        os.chmod(new_script_path, os.stat(new_script_path).st_mode | stat.S_IEXEC)

        return new_script_path

    def upload_scripts(
        self,
        scripts: list[str] | None = None,
        commands: list[str] | None = None,
    ) -> tuple[str, str]:
        """Upload script files via SFTP and generate a wrapper to run them.

        Creates a wrapper script (run.sh) that executes each uploaded script
        in order, followed by any extra lines. All files are uploaded to a
        temporary directory on the remote machine.

        Args:
            scripts: Local script file paths to upload and execute.
            commands: Shell commands to execute after the scripts.

        Returns:
            Tuple of (remote_dir, shell command to execute the wrapper).
        """
        if not (scripts or commands):
            raise RuntimeError("No scripts, commands, or extra lines provided")

        # shortcut: if no scripts and all commands are one-liner, do no upload, but return command to
        # run directly.
        if not scripts and all("\n" not in cmd for cmd in (commands or [])):
            command = "; ".join(commands or [])
            logger.debug("No scripts, running commands directly: %s", command)
            return ("", command)

        with tempfile.TemporaryDirectory() as _td:
            temp_dir = Path(_td)
            paths_to_upload: list[str] = []

            # extract path to folder; all scripts are relative to this path
            wrapper_contents = ['SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"']

            wrapper_contents.append("\n# # # # # # # # SCRIPTS # # # # # # # #\n")

            # copy files over, make them executable
            for script_ in scripts or []:
                if not (script_path := Path(script_)).is_file():
                    raise ValueError(f"Script {script_path} does not exist")

                # copy file to temp direcory, make executable, etc
                new_script_path = self._prepare_file(
                    temp_dir=temp_dir,
                    contents=script_path.read_text(encoding="utf-8"),
                    script_name=script_path.name,
                )
                paths_to_upload.append(str(new_script_path))
                wrapper_contents.append(f"${{SCRIPT_DIR}}/{new_script_path.name}")

            # separator between script paths and commands
            wrapper_contents.append("\n# # # # # # # # COMMANDS# # # # # # # #\n")

            # add command after the script paths
            for c in commands or []:
                wrapper_contents.append(c)

            # now write the wrapper file
            wrapper_path = self._prepare_file(
                temp_dir=temp_dir,
                contents="\n".join(wrapper_contents),
                script_name="run.sh",
            )
            paths_to_upload.append(str(wrapper_path))

            remote_dir, _ = self.upload_files(paths_to_upload)

        return remote_dir, f"bash {remote_dir}/{wrapper_path.name}"


def import_ssh_key_to_ec2(key_name: str, region: str, private_key_path: str) -> str:
    """
    Imports an SSH public key to EC2 as a key pair.

    Args:
        key_name: The name to assign to the key pair in EC2
        region: AWS region where to import the key
        private_key_path: Path to the SSH private key file (defaults to ~/.ssh/id_rsa)

    Returns:
        The key pair ID if the import was successful.
    """
    from .aws_instance import ClientUtils

    client = ClientUtils.get_ec2_client(region=region)
    assert client, "EC2 client is required"

    if not private_key_path:
        home_dir = os.path.expanduser("~")
        for key_name in DEFAULT_PRIVATE_KEY_NAMES:
            private_key_path = os.path.join(home_dir, ".ssh", key_name)
            if os.path.isfile(private_key_path):
                break

    if not os.path.isfile(private_key_path):
        raise ValueError(f"Private key file not found at {private_key_path}")

    try:
        with open(private_key_path, "r") as key_file:
            private_key_material = key_file.read().strip()

        # Derive public key from private key via ssh-keygen
        ssh_public_key_path = f"{private_key_path}.pub"
        try:
            subprocess.run(
                ["ssh-keygen", "-y", "-f", private_key_path],
                check=True,
                stdout=open(ssh_public_key_path, "w"),
                stderr=subprocess.PIPE,
            )
            with open(ssh_public_key_path, "r") as pub_key_file:
                public_key_material = pub_key_file.read().strip()
        except subprocess.CalledProcessError as e:
            raise ValueError(f"Failed to generate public key: {e.stderr.decode()}")

        logger.info(f"Generated public key from private key and saved to {ssh_public_key_path}")
    except Exception as e:
        logger.error(f"Failed to generate public key from private key: {str(e)}")
        raise ValueError(f"Could not generate public key from private key: {str(e)}")

    # Build a deterministic key name from hashes of both private and public material
    h = hashlib.sha256(private_key_material.encode()).hexdigest()
    key_name = f"{key_name}-{h}"

    with open(ssh_public_key_path, "r") as key_file:
        public_key_material = key_file.read().strip()

    h = hashlib.sha256(public_key_material.encode()).hexdigest()
    key_name = f"{key_name}-{h}"

    try:
        try:
            client.describe_key_pairs(KeyNames=[key_name])
            logger.info(f"Key pair '{key_name}' already exists in region {region}. Skipping import.")
            return key_name
        except client.exceptions.ClientError:
            pass

        response = client.import_key_pair(KeyName=key_name, PublicKeyMaterial=public_key_material)

        if response["KeyFingerprint"] is None:
            raise ValueError(f"Failed to import key pair '{key_name}' to region {region}")

        logger.info(f"Successfully imported key pair '{key_name}' to region {region}")
        return key_name

    except Exception as e:
        logger.error(f"Error importing SSH key: {str(e)}")
        raise e
